apiVersion: v1
kind: ConfigMap
metadata:
  name: test-inputs
  namespace: default
data:
  enable: "true"
  replicas: "1"

---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: example
spec:
  revision: 3
  inputs:
  - apiVersion: v1
    kind: ConfigMap
    namespace: "default"
    name: "test-inputs"
  generator:
    image: "joolshevsoak.azurecr.io/eno-example:v11"
