# Modify the synthesizer to set the "status" key to some other value - the composition will never become ready.

apiVersion: eno.azure.io/v1
kind: Synthesizer
metadata:
  name: readiness-example
spec:
  image: docker.io/ubuntu:latest
  command:
  - /bin/bash
  - -c
  - |
    echo '
      {
        "apiVersion":"config.kubernetes.io/v1",
        "kind":"ResourceList",
        "items":[
          {
            "apiVersion":"v1",
            "data":{"status":"Ready"},
            "kind":"ConfigMap",
            "metadata":{
              "name":"readiness-example",
              "namespace": "default",
              "annotations": {
                "eno.azure.io/readiness": "self.data.status == \"Ready\""
              }
            }
          }
        ]
      }'
---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: readiness-example
  namespace: default
spec:
  synthesizer:
    name: readiness-example
