# TODO: Set up service account, etc.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-controller
  labels:
    app: eno-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno-controller
  template:
    metadata:
      labels:
        app: eno-controller
    spec:
      containers:
      - name: controller
        image: ${CONTROLLER_IMAGE}
        env:
        - name: WRAPPER_IMAGE
          value: ${WRAPPER_IMAGE}

---

# Optionally mount /etc/upstream-kubeconfig to reconcile against another cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-reconciler
  labels:
    app: eno-reconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno-reconciler
  template:
    metadata:
      labels:
        app: eno-reconciler
    spec:
      containers:
      - name: controller
        image: ${RECONCILER_IMAGE}
        env:
        - name: WRAPPER_IMAGE
          value: ${WRAPPER_IMAGE}
        - name: NAMESPACE
          value: default

---

apiVersion: eno.azure.io/v1
kind: Generator
metadata:
  name: simple-example
spec:
  image: ${EXAMPLE_IMAGE}

---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: example
  namespace: default
spec:
  revision: 1
  inputs:
  - apiVersion: v1
    kind: ConfigMap
    namespace: "default"
    name: "test-inputs"
  generator:
    name: simple-example

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-inputs
  namespace: default
data:
  enable: "true"
  replicas: "1"
