#!/bin/bash

set -e
source ./images/tags.env


# Any global/shared resources (default namespace) defined here
cat > loadtest.yaml <<YAML
# generated by loadgen.sh

apiVersion: eno.azure.io/v1
kind: Generator
metadata:
  name: simple-example
spec:
  image: ${EXAMPLE_IMAGE}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-controller
  labels:
    app: eno-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno-controller
  template:
    metadata:
      labels:
        app: eno-controller
    spec:
      containers:
      - name: controller
        image: ${CONTROLLER_IMAGE}
        env:
        - name: WRAPPER_IMAGE
          value: ${WRAPPER_IMAGE}
YAML

for i in {1..10}; do
	cat >> loadtest.yaml <<YAML
---

apiVersion: v1
kind: Namespace
metadata:
  name: loadgen-${i}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-loadgen-${i}
subjects:
- kind: ServiceAccount
  name: default
  namespace: loadgen-${i}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-reconciler
  namespace: loadgen-${i}
  labels:
    app: eno-reconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno-reconciler
  template:
    metadata:
      labels:
        app: eno-reconciler
    spec:
      containers:
      - name: controller
        image: ${RECONCILER_IMAGE}
        env:
        - name: WRAPPER_IMAGE
          value: ${WRAPPER_IMAGE}
        - name: NAMESPACE
          value: loadgen-${i}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-inputs
  namespace: loadgen-${i}
data:
  enable: "true"
  namespace: "loadgen-${i}"
  replicas: "3000"

---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: loadgen
  namespace: loadgen-${i}
spec:
  revision: 10
  reconcileInterval: 10m
  inputs:
  - name: test-inputs
    resource:
      apiVersion: v1
      kind: ConfigMap
      namespace: "loadgen-${i}"
      name: "test-inputs"
  generator:
    name: simple-example
YAML
done
