apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-controller
  labels:
    app: eno-controller
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: eno-controller
  template:
    metadata:
      labels:
        app: eno-controller
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: eno-controller
        image: $REGISTRY/eno-controller:$TAG
        env:
          - name: PPROF_ADDR
            value: ":8888"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-reconciler
  labels:
    app: eno-reconciler
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: eno-reconciler
  template:
    metadata:
      labels:
        app: eno-reconciler
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: eno-reconciler
        image: $REGISTRY/eno-reconciler:$TAG
        args:
        - --qps=1000
        - --remote-qps=1000
        env:
          - name: PPROF_ADDR
            value: ":8888"
          - name: INSECURE_LOG_PATCH
            value: "true"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
