apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-controller
  labels:
    app: eno-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno-controller
  template:
    metadata:
      labels:
        app: eno-controller
    spec:
      containers:
      - name: eno-controller
        image: $REGISTRY/eno-controller:$TAG
        env:
          - name: PPROF_ADDR
            value: ":8888"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-reconciler
  labels:
    app: eno-reconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno-reconciler
  template:
    metadata:
      labels:
        app: eno-reconciler
    spec:
      containers:
      - name: eno-reconciler
        image: $REGISTRY/eno-reconciler:$TAG
        args:
        - --qps=1000
        - --remote-qps=1000
        env:
          - name: PPROF_ADDR
            value: ":8888"
          - name: INSECURE_LOG_PATCH
            value: "true"
