apiVersion: eno.azure.io/v1
kind: Synthesizer
metadata:
  name: churn-test-synth
spec:
  image: docker.io/ubuntu:latest
  execTimeout: 1m
  command:
  - /bin/bash
  - -c
  - |
      n=200
      tr -dc A-Za-z0-9 </dev/urandom | head -c 4096 > rando
      echo -n "{\"apiVersion\":\"config.kubernetes.io/v1\",\"kind\":\"ResourceList\",\"items\":["
      for i in $(seq $n); do
        echo -n "{
          \"apiVersion\": \"v1\",
          \"kind\": \"ConfigMap\",
          \"metadata\": { \"name\": \"churn-test-${i}\", \"namespace\": \"default\", \"annotations\": { \"eno.azure.io/reconcile-interval\": \"30s\" } },
          \"data\": { \"foo\": \"$(cat rando)\" }
        }"
        if [[ $i == $n ]]; then
          echo "]}"
        else
          echo ","
        fi
      done
---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: churn-test
spec:
  synthesizer:
    name: churn-test-synth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-test-roller
  labels:
    app: churn-test-roller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: churn-test-roller
  template:
    metadata:
      labels:
        app: churn-test-roller
    spec:
      containers:
      - name: roller
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          n=0
          while true; do
            timeout="61s"
            if [[ $(($n % 2)) == 1 ]]; then
              timeout="60s"
            fi

            kubectl patch synthesizers churn-test-synth --type=merge --patch "{\"spec\":{\"execTimeout\": \"$timeout\"}}"
            n=$(($n + 1))
            sleep 10
          done
