apiVersion: eno.azure.io/v1
kind: Synthesizer
metadata:
  name: load-test-synth
spec:
  image: docker.io/ubuntu:latest
  execTimeout: 1m
  command:
  - /bin/bash
  - -c
  - |
      n=12000
      tr -dc A-Za-z0-9 </dev/urandom | head -c 4096 > rando
      echo -n "{\"apiVersion\":\"config.kubernetes.io/v1\",\"kind\":\"ResourceList\",\"items\":["
      for i in $(seq $n); do
        echo -n "{
          \"apiVersion\": \"v1\",
          \"kind\": \"ConfigMap\",
          \"metadata\": { \"name\": \"test-cm-${i}\", \"namespace\": \"default\", \"annotations\": { \"eno.azure.io/reconcile-interval\": \"30s\" } },
          \"data\": { \"foo\": \"$(cat rando)\" }
        }"
        if [[ $i == $n ]]; then
          echo "]}"
        else
          echo ","
        fi
      done
---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: load-test
spec:
  synthesizer:
    name: load-test-synth
