apiVersion: eno.azure.io/v1
kind: Synthesizer
metadata:
  name: load-test-synth
spec:
  image: docker.io/ubuntu:latest
  command:
  - /bin/bash
  - -c
  - |
      n=23
      echo -n '['
      for i in $(seq $n); do
        echo -n "{
          \"apiVersion\": \"v1\",
          \"kind\": \"ConfigMap\",
          \"metadata\": { \"name\": \"test-cm-${i}\", \"namespace\": \"default\", \"annotations\": { \"eno.azure.io/reconcile-interval\": \"10s\" } },
          \"data\": { \"foo\": \"bar\" }
        }"
        if [[ $i == $n ]]; then
          echo "]"
        else
          echo ","
        fi
      done

---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: load-test
spec:
  synthesizer:
    name: load-test-synth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: roller
  labels:
    app: roller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roller
  template:
    metadata:
      labels:
        app: roller
    spec:
      containers:
      - name: roller
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          n=0
          while true; do
            timeout="10s"
            if [[ $(($n % 2)) == 1 ]]; then
              timeout="11s"
            fi

            kubectl patch synthesizers load-test-synth --type=merge --patch "{\"spec\":{\"timeout\": \"$timeout\"}}"
            n=$(($n + 1))
            sleep 120
          done
