package generation

import (
	"context"
	"fmt"

	"github.com/go-logr/logr"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	apiv1 "github.com/Azure/eno/api/v1"
	"github.com/Azure/eno/conf"
)

// TODO: What should deleted completed or unnecessary jobs?

type Controller struct {
	config *conf.Config
	client client.Client
	logger logr.Logger
}

func NewController(mgr ctrl.Manager, config *conf.Config) error {
	c := &Controller{
		config: config,
		client: mgr.GetClient(),
		logger: mgr.GetLogger(),
	}

	_, err := ctrl.NewControllerManagedBy(mgr).
		For(&apiv1.Composition{}).
		Owns(&batchv1.Job{}).
		Build(c)

	return err
}

func (c *Controller) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	comp := &apiv1.Composition{}
	err := c.client.Get(ctx, req.NamespacedName, comp)
	if err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(fmt.Errorf("getting composition resource: %w", err))
	}

	// Skip cases in which the GeneratedResources have already been created
	if comp.Spec.Generator == nil {
		return ctrl.Result{}, nil // can't generate the composed resources without a generator
	}
	cond := meta.FindStatusCondition(comp.Status.Conditions, apiv1.CompositionGeneratedConditionType)
	if cond != nil && cond.ObservedGeneration == comp.Generation && cond.Status == metav1.ConditionTrue {
		return ctrl.Result{}, nil // already in sync
	}

	// We're starting generation, reflect that in the resource's status
	meta.SetStatusCondition(&comp.Status.Conditions, metav1.Condition{
		Type:               apiv1.CompositionGeneratedConditionType,
		Status:             metav1.ConditionFalse,
		ObservedGeneration: comp.Generation,
		LastTransitionTime: metav1.Now(),
		Reason:             "JobPending",
		Message:            "resources will be generated by a job",
	})
	err = c.client.Status().Update(ctx, comp)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("updating composition resource status: %w", err)
	}

	// Avoid creating duplicate jobs
	jobList := &batchv1.JobList{}
	err = c.client.List(ctx, jobList, client.MatchingLabels{"composition": comp.Name, "composition-resource-version": comp.ResourceVersion}, client.Limit(1))
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("listing current jobs: %w", err)
	}
	if len(jobList.Items) > 0 {
		return ctrl.Result{}, nil
	}

	// TODO: avoid race condition here

	// Create a job to generate the resouces!
	job := c.newJob(comp)
	err = c.client.Create(ctx, job)
	if err != nil {
		return ctrl.Result{}, client.IgnoreAlreadyExists(fmt.Errorf("creating generation job: %w", err))
	}
	c.logger.Info("created job to generate resources for composition", "jobName", job.Name)

	return ctrl.Result{}, nil
}

func (c *Controller) newJob(comp *apiv1.Composition) *batchv1.Job {
	var (
		parallelism       = int32(1)
		timeout           = int64(c.config.JobTimeout.Seconds())
		ttl               = int32(c.config.JobTTL.Seconds())
		wrapperVolumeName = "wrapper"
	)

	job := &batchv1.Job{}
	if err := controllerutil.SetControllerReference(comp, job, c.client.Scheme()); err != nil {
		panic(fmt.Sprintf("unable to set owner reference: %s", err))
	}
	job.Labels = map[string]string{"composition": comp.Name, "composition-resource-version": comp.ResourceVersion}
	job.GenerateName = comp.Name + "-"
	job.Namespace = c.config.JobNS
	job.Spec.Parallelism = &parallelism
	job.Spec.ActiveDeadlineSeconds = &timeout
	job.Spec.TTLSecondsAfterFinished = &ttl
	job.Spec.Template = corev1.PodTemplateSpec{
		Spec: corev1.PodSpec{
			RestartPolicy: corev1.RestartPolicyNever,
			InitContainers: []corev1.Container{{
				Name:  "setup",
				Image: c.config.WrapperImage,
				Command: []string{
					"/eno-wrapper", "--install=/wrapper/eno-wrapper",
				},
				VolumeMounts: []corev1.VolumeMount{{
					Name:      wrapperVolumeName,
					MountPath: "/wrapper",
				}},
			}},
			Containers: []corev1.Container{{
				Name:  "generator",
				Image: comp.Spec.Generator.Image,
				Command: []string{
					"/wrapper/eno-wrapper", "--generate",
				},
				VolumeMounts: []corev1.VolumeMount{{
					Name:      wrapperVolumeName,
					MountPath: "/wrapper",
					ReadOnly:  true,
				}},
				Env: []corev1.EnvVar{
					{
						Name:  "COMPOSITION_NAME",
						Value: comp.Name,
					},
					{
						Name:  "COMPOSITION_RESOURCE_VERSION",
						Value: comp.ResourceVersion,
					},
				},
			}},
			Volumes: []corev1.Volume{{
				Name:         wrapperVolumeName,
				VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}},
			}},
		},
	}

	return job
}
