package generation

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"

	"github.com/go-logr/logr"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	apiv1 "github.com/Azure/eno/api/v1"
	"github.com/Azure/eno/conf"
)

type Controller struct {
	config *conf.Config
	client client.Client
	logger logr.Logger
}

func NewController(mgr ctrl.Manager, config *conf.Config) error {
	c := &Controller{
		config: config,
		client: mgr.GetClient(),
		logger: mgr.GetLogger(),
	}

	_, err := ctrl.NewControllerManagedBy(mgr).
		For(&apiv1.Composition{}).
		Owns(&batchv1.Job{}).
		Build(c)

	return err
}

func (c *Controller) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	comp := &apiv1.Composition{}
	err := c.client.Get(ctx, req.NamespacedName, comp)
	if err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(fmt.Errorf("getting composition resource: %w", err))
	}

	if comp.Spec.Generator == nil {
		return ctrl.Result{}, nil // can't generate the composed resources without a generator
	}

	// Avoid creating duplicate jobs
	job := c.newJob(comp)
	current := &batchv1.Job{}
	err = c.client.Get(ctx, client.ObjectKeyFromObject(job), current)
	if client.IgnoreNotFound(err) != nil {
		return ctrl.Result{}, fmt.Errorf("listing current jobs: %w", err)
	}
	if err == nil { // !404
		return c.updateDeadlockCondition(ctx, comp, current)
	}

	// Skip cases in which the GeneratedResources have already been created
	cond := meta.FindStatusCondition(comp.Status.Conditions, apiv1.GeneratedConditionType)
	if cond != nil && cond.ObservedGeneration == comp.Generation && cond.Status == metav1.ConditionTrue {
		return ctrl.Result{}, nil // already in sync
	}

	// We're starting generation, reflect that in the resource's status
	meta.SetStatusCondition(&comp.Status.Conditions, metav1.Condition{
		Type:               apiv1.GeneratedConditionType,
		Status:             metav1.ConditionFalse,
		ObservedGeneration: comp.Generation,
		LastTransitionTime: metav1.Now(),
		Reason:             "JobPending",
		Message:            "resources will be generated by a job",
	})
	err = c.client.Status().Update(ctx, comp)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("updating composition resource status: %w", err)
	}

	// Create a job to generate the resouces!
	err = c.client.Create(ctx, job)
	if err != nil {
		return ctrl.Result{}, client.IgnoreAlreadyExists(fmt.Errorf("creating generation job: %w", err))
	}
	c.logger.Info("created job to generate resources for composition", "jobName", job.Name)

	return ctrl.Result{}, nil
}

func (c *Controller) newJob(comp *apiv1.Composition) *batchv1.Job {
	var (
		parallelism       = int32(1)
		timeout           = int64(c.config.JobTimeout.Seconds())
		ttl               = int32(c.config.JobTTL.Seconds())
		wrapperVolumeName = "wrapper"
	)

	hash := sha256.New()
	fmt.Fprintf(hash, "%s-%d", comp.Name, comp.Generation)
	hashStr := hex.EncodeToString(hash.Sum(nil))[:7]

	job := &batchv1.Job{}
	if err := controllerutil.SetControllerReference(comp, job, c.client.Scheme()); err != nil {
		panic(fmt.Sprintf("unable to set owner reference: %s", err))
	}
	job.Name = "generate-" + hashStr
	job.Namespace = c.config.JobNS
	job.Spec.Parallelism = &parallelism
	job.Spec.TTLSecondsAfterFinished = &ttl
	job.Spec.Template = corev1.PodTemplateSpec{
		Spec: corev1.PodSpec{
			RestartPolicy:         corev1.RestartPolicyNever,
			ActiveDeadlineSeconds: &timeout,
			InitContainers: []corev1.Container{{
				Name:  "setup",
				Image: c.config.WrapperImage,
				Command: []string{
					"/eno-wrapper", "--install=/wrapper/eno-wrapper",
				},
				VolumeMounts: []corev1.VolumeMount{{
					Name:      wrapperVolumeName,
					MountPath: "/wrapper",
				}},
			}},
			Containers: []corev1.Container{{
				Name:  "generator",
				Image: comp.Spec.Generator.Image,
				Command: []string{
					"/wrapper/eno-wrapper", "--generate",
				},
				VolumeMounts: []corev1.VolumeMount{{
					Name:      wrapperVolumeName,
					MountPath: "/wrapper",
					ReadOnly:  true,
				}},
				Env: []corev1.EnvVar{
					{
						Name:  "COMPOSITION_NAME",
						Value: comp.Name,
					},
					{
						Name:  "COMPOSITION_RESOURCE_VERSION", // TODO: Use generation
						Value: comp.ResourceVersion,
					},
				},
			}},
			Volumes: []corev1.Volume{{
				Name:         wrapperVolumeName,
				VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}},
			}},
		},
	}

	return job
}

func (c *Controller) updateDeadlockCondition(ctx context.Context, comp *apiv1.Composition, job *batchv1.Job) (ctrl.Result, error) {
	failed := job.Spec.BackoffLimit != nil && job.Status.Active+job.Status.Failed == *job.Spec.BackoffLimit

	expected := &metav1.Condition{
		Type:               apiv1.DeadlockedConditionType,
		ObservedGeneration: comp.Generation,
	}
	if failed {
		expected.Status = metav1.ConditionTrue
		expected.Reason = "JobDeadlocked"
		expected.Message = "Job has reached its retry limit and cannot successfully complete"
	} else {
		expected.Status = metav1.ConditionFalse
		expected.Reason = "JobNotDeadlocked"
		expected.Message = "Job is not in a deadlock condition"
	}

	cond := meta.FindStatusCondition(comp.Status.Conditions, apiv1.DeadlockedConditionType)
	if cond != nil && cond.Status == expected.Status {
		return ctrl.Result{}, nil
	}

	expected.LastTransitionTime = metav1.Now()
	meta.SetStatusCondition(&comp.Status.Conditions, *expected)
	return ctrl.Result{}, c.client.Status().Update(ctx, comp)
}
