# Run build.sh to push the synthesizer to $REGISTRY before `kubectl apply`ing this manifest
#
# Then, `kubectl edit cm eno-input-example` to set replicas=2. The deployment should be updated almost immediately.

apiVersion: v1
kind: ConfigMap
metadata:
  name: eno-input-example
data:
  replicas: "1"

---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: go-synth-example
spec:
  synthesizer:
    name: go-synth-example
  bindings:
    - key: example-input
      resource:
        name: eno-input-example
        namespace: default
