name: Kubernetes Version Compatibility Tests
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  buildMatrix:
    name: Prepare Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrixbuild.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Generate test matrix
        id: matrixbuild
        run: echo "matrix=$(./hack/build-k8s-matrix.sh)" >> $GITHUB_OUTPUT

      - name: Build the test binary
        id: testbuild
        run: go test -c -o eno-tests ./internal/controllers/reconciliation

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          retention-days: 1
          path: eno-tests

  test:
    name: Kubernetes 1.${{ matrix.downstreamApiserverMinorVersion }}
    needs: buildMatrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        downstreamApiserverMinorVersion: ${{ fromJson(needs.buildMatrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-artifacts

      - name: Download kubebuilder assets
        run: |
          echo "UPSTREAM_KUBEBUILDER_ASSETS=$(./hack/download-k8s.sh)" >> $GITHUB_ENV
          echo "DOWNSTREAM_KUBEBUILDER_ASSETS=$(./hack/download-k8s.sh ${{ matrix.downstreamApiserverMinorVersion }})" >> $GITHUB_ENV

      - name: Run tests
        run: |
          chmod +x eno-tests
          cd internal/controllers/reconciliation
          ../../../eno-tests -test.v
        env:
          DOWNSTREAM_VERSION_MINOR: "${{ matrix.downstreamApiserverMinorVersion }}"
