name: Smoke Tests
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Create Kind cluster
        uses: helm/kind-action@v1

      - name: Run tests
        timeout-minutes: 5
        run: ./hack/smoke-test.sh
