name: Smoke Tests
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Kind cluster
        uses: helm/kind-action@v1

      - name: Wait for apiserver
        run: |
          kind export kubeconfig --name chart-testing
          while true; do
              kubectl api-resources
              if [[ $? -eq 0 ]]; then
                  break
              else
                  sleep 1
              fi
          done

      - name: Build images
        run: |
          set -e
          export REGISTRY=localhost
          export SKIP_PUSH=yes

          echo "--- building eno..."
          ./dev/build.sh

          for i in ./examples/*/build.sh; do
            echo "--- running $i..."
            $i
          done

          # Copy images to kind
          for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep localhost); do
            echo "--- pushing $image"
            kind load docker-image --name chart-testing $image
          done

      - name: Run tests
        timeout-minutes: 3
        run: ./hack/smoke-test.sh
