name: Smoke Tests
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  test:
    name: Apply Examples (${{ matrix.config.name }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Default
            disable_ssa: "false"
          - name: Disable SSA
            disable_ssa: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Create Kind cluster
        uses: helm/kind-action@v1

      - name: Wait for apiserver
        run: |
          kind export kubeconfig --name chart-testing
          while true; do
              kubectl api-resources
              if [[ $? -eq 0 ]]; then
                  break
              else
                  sleep 1
              fi
          done

      - name: Build Eno images
        env:
          REGISTRY: localhost
          SKIP_PUSH: "yes"
          DISABLE_SSA: "${{ matrix.config.disable_ssa }}"
        run: |
          echo "--- building eno..."
          ./dev/build.sh

      - name: Build Example images
        env:
          REGISTRY: localhost
          SKIP_PUSH: "yes"
        run: |
          for i in ./examples/*/build.sh; do
            echo "--- running $i..."
            $i
          done

      - name: Load images into Kind cluster
        run: |
          for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep localhost); do
            echo "--- pushing $image"
            kind load docker-image --name chart-testing $image
          done

      - name: Run tests
        timeout-minutes: 3
        run: ./hack/smoke-test.sh
