name: Go Unit Tests
on:
  push:
  pull_request:
    branches:
      - main
      - official/**
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download k8s
        run: echo "KUBEBUILDER_ASSETS=$(./hack/download-k8s.sh)" >> $GITHUB_ENV

      - name: Run tests
        run: go test -v ./...

